# Generated by Django 2.0.4 on 2018-04-13 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('dateNaissance', models.DateField(blank=True, null=True)),
                ('finPeriodeEssai', models.DateField(blank=True)),
                ('photo', models.ImageField(upload_to='uploads/', blank=True, null=True,default ='uploads/Chrysanthemum.jpg')),
                ('dossierCompetence', models.FileField(upload_to='uploads/', blank=True, null=True)),
                ('cv', models.FileField(upload_to='uploads/',blank=True, null=True)),
                ('dateEntreeDansLeGroupe', models.DateField(blank=True)),
                ('francais', models.BooleanField()),
                ('dateValiditeTitreDeSejour', models.DateField(blank=True)),
                ('salaire', models.IntegerField()),
                ('telephone', models.CharField(max_length=100, blank=True)),
                ('emailAKKA', models.EmailField(blank=True, null=True)),
                ('emailPerso', models.EmailField(blank=True, max_length=254, null=True)),
                ('adresse', models.CharField(blank=True, max_length=150)),
                ('codePostal', models.IntegerField(blank=True, null=True)),
                ('ville', models.CharField(max_length=100,blank=True)),
                ('anneeExperience', models.DateField(blank=True)),
                ('niveauDiplome', models.CharField(choices=[('Niveau B+2/3 ou inférieur', 'Niveau B+2/3 ou inférieur'), ('B+2/3', 'B+2/3'), ('B+5', 'B+5'), ('B+7 ou plus', 'B+7 ou plus')], default='B+5', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('mdp', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('Business Manager', 'Business Manager'), ('Chargé de recrutement', 'Chargé de recrutement'), ("Assistant d'agence", "Assistant d'agence"), ('Responsable des ressources humaines', 'Responsable des ressources humaines'), ('Contrôleur de gestion', 'Contrôleur de gestion'), ('Administrateur', 'Administrateur')], max_length=50)),
                ('superieur', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Akkannuaire.Utilisateur')),
            ],
            bases=('Akkannuaire.utilisateur',),
        ),
        migrations.CreateModel(
            name='AssistantAgence',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Akkannuaire.Utilisateur')),
            ],
            bases=('Akkannuaire.utilisateur',),
        ),
        migrations.CreateModel(
            name='BusinessManager',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Akkannuaire.Utilisateur')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Akkannuaire.BusinessManager')),
            ],
            bases=('Akkannuaire.utilisateur',),
        ),
        migrations.CreateModel(
            name='ChargeDeRecrutement',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Akkannuaire.Utilisateur')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Akkannuaire.ChargeDeRecrutement')),
            ],
            bases=('Akkannuaire.utilisateur',),
        ),
        migrations.CreateModel(
            name='ControleurDeGestion',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Akkannuaire.Utilisateur')),
            ],
            bases=('Akkannuaire.utilisateur',),
        ),
        migrations.CreateModel(
            name='ResponsableRessourceHumaine',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Akkannuaire.Utilisateur')),
            ],
            bases=('Akkannuaire.utilisateur',),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultant',
            name='assistantDAgence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Akkannuaire.AssistantAgence'),
        ),
        migrations.AddField(
            model_name='consultant',
            name='businessManager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Akkannuaire.BusinessManager'),
        ),
        migrations.AddField(
            model_name='consultant',
            name='chargeDeRecrutement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Akkannuaire.ChargeDeRecrutement'),
        ),
    ]
