# Generated by Django 2.0.4 on 2018-04-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Akkannuaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='telephone',
            field=models.CharField(max_length=100),
        ),
    ]
