# Generated by Django 2.0.4 on 2018-05-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Akkannuaire', '0003_auto_20180527_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='dateValiditeTitreDeSejour',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='telephone',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
