# Generated by Django 2.0.4 on 2018-05-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Akkannuaire', '0004_auto_20180529_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='cv',
            field=models.FileField(blank=True, default='default.jpg', null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='dossierCompetence',
            field=models.FileField(blank=True, default='default.jpg', null=True, upload_to='uploads/'),
        ),
    ]
